//! Command-tag grammar in user messages.
//!
//! Claude Code wraps slash commands, their output and skill prompts in XML-ish
//! tags. This is the one place that knows how to read them: what to show for
//! a user message (`user_text`) and how to pull a command name out of one.

pub fn parse_command_name(text: &str) -> Option<&str> {
    let trimmed = text.trim();

    if let Some(start) = trimmed.find("<command-name>")
        && let Some(end) = trimmed.find("</command-name>")
    {
        let content_start = start + "<command-name>".len();
        if content_start < end {
            return Some(&trimmed[content_start..end]);
        }
    }

    None
}

pub fn parse_command_name_and_args(text: &str) -> Option<String> {
    let trimmed = text.trim();
    let command_name = parse_command_name(trimmed)?;

    if let Some(args_start) = trimmed.find("<command-args>")
        && let Some(args_end) = trimmed.find("</command-args>")
    {
        let args_content_start = args_start + "<command-args>".len();
        if args_content_start < args_end {
            let args = trimmed[args_content_start..args_end].trim();
            if !args.is_empty() {
                return Some(format!("{} {}", command_name, args));
            }
        }
    }

    Some(command_name.to_string())
}

/// Process user message text to handle command-related XML tags.
/// Returns None if the message should be skipped entirely (e.g., empty local-command-stdout).
pub fn user_text(text: &str) -> Option<String> {
    let trimmed = text.trim();

    // Check for local-command-caveat - skip these system messages entirely
    if trimmed.starts_with("<local-command-caveat>") && trimmed.ends_with("</local-command-caveat>")
    {
        return None;
    }

    // Check for empty or whitespace-only local-command-stdout - skip these entirely
    if trimmed.starts_with("<local-command-stdout>") && trimmed.ends_with("</local-command-stdout>")
    {
        let tag_start = "<local-command-stdout>".len();
        let tag_end = trimmed.len() - "</local-command-stdout>".len();
        let inner = &trimmed[tag_start..tag_end];
        if inner.trim().is_empty() {
            return None;
        }
        // Non-empty local-command-stdout: show the content without the tags
        return Some(inner.trim().to_string());
    }

    // Check if this is a command message with <command-name> tag
    if let Some(command_name) = parse_command_name(trimmed) {
        // Skip /clear commands - internal context-clearing, not meaningful to display
        if command_name == "/clear" {
            return None;
        }

        return parse_command_name_and_args(trimmed);
    }

    // Skill invocation expanded prompts - show description instead of full prompt
    if trimmed.starts_with("Base directory for this skill:") {
        let description = trimmed
            .lines()
            .skip(1)
            .find(|l| !l.trim().is_empty())
            .unwrap_or("invoked");
        return Some(format!("*Skill: {}*", description));
    }

    Some(text.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_text_skips_local_command_caveat() {
        let caveat = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>";
        assert_eq!(user_text(caveat), None);
    }

    #[test]
    fn user_text_skips_local_command_caveat_with_whitespace() {
        let caveat = "  <local-command-caveat>Some caveat text</local-command-caveat>  ";
        assert_eq!(user_text(caveat), None);
    }

    #[test]
    fn user_text_preserves_normal_text() {
        assert_eq!(user_text("Hello world"), Some("Hello world".to_string()));
    }

    #[test]
    fn user_text_skips_empty_stdout() {
        assert_eq!(
            user_text("<local-command-stdout></local-command-stdout>"),
            None
        );
        assert_eq!(
            user_text("<local-command-stdout>   </local-command-stdout>"),
            None
        );
    }

    #[test]
    fn user_text_extracts_nonempty_stdout() {
        assert_eq!(
            user_text("<local-command-stdout>output here</local-command-stdout>"),
            Some("output here".to_string())
        );
    }

    #[test]
    fn user_text_skips_clear_command() {
        assert_eq!(user_text("<command-name>/clear</command-name>"), None);
        // Also skip clear with command-message and command-args tags
        assert_eq!(
            user_text(
                "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>"
            ),
            None
        );
    }

    #[test]
    fn user_text_extracts_other_command_names() {
        assert_eq!(
            user_text("<command-name>/help</command-name>"),
            Some("/help".to_string())
        );
    }

    #[test]
    fn user_text_condenses_skill_invocation() {
        let skill_msg = "Base directory for this skill: /Users/raine/.claude/skills/consult\n\nConsult an external LLM with the user's query.\n\n**Arguments:** `how to add more aliases?`";
        assert_eq!(
            user_text(skill_msg),
            Some("*Skill: Consult an external LLM with the user's query.*".to_string())
        );
    }

    #[test]
    fn user_text_skill_invocation_fallback() {
        let skill_msg = "Base directory for this skill: /path/to/skill";
        assert_eq!(user_text(skill_msg), Some("*Skill: invoked*".to_string()));
    }
}
